version: '3'

services:
  db:
    image: mongo:5.0
    container_name: school-management-mongodb
    ports:
      - ${MONGODB_PORT}:27017
    restart: always

  app:
    image: school-management-app
    build: .
    tty: true
    links:
      - db
    volumes:
      - .:/nestjs-task-manager
      - ./node_modules:/nestjs-task-manager/node_modules
    ports:
      - ${PORT}:3000
    depends_on:
      - db
    restart: always
    command: bash -c "npm run start:dev"
