version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - .docker/data/db:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=root
